#!/usr/bin/env python3
"""Summarise a tegrastats log over the window where the GPU was working.

The Gate 3 evidence table started life as three jtop screenshots, read off at
three arbitrary moments. Screenshots cannot answer the question the table is
there to answer -- did the GPU clock *hold* at the power mode's ceiling, or
sag partway through -- and they cannot be regenerated by anyone else. A 1 Hz
tegrastats log can, so this parses one.

    sudo tegrastats --interval 1000 --logfile run.log   # in one shell
    ...                                                 # the run, in another
    sudo tegrastats --stop
    python3 tools/summarize_tegrastats.py run.log

Samples are split into busy and idle by GPU utilisation, because a log always
brackets the run with idle time and mixing the two produces an average that
describes neither. The split is reported so the choice is visible.

One sample at each edge of each busy stretch is then dropped. tegrastats
reports the *mean* over its interval, so a sample straddling the start or end
of the run averages a working GPU with an idle one. Left in, those samples
put impossible values in the minimum column -- 0% CPU and 11.5 W during an
inference -- and make the clock look like it sagged when it did not.
"""

from __future__ import annotations

import argparse
import json
import os
import re
import sys
from typing import Dict, List, Optional

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from telemetry.metrics import percentile

# Fields vary between L4T releases, so each is matched independently and a
# missing one is skipped rather than failing the parse.
PATTERNS = {
    "ram_used_mb": re.compile(r"RAM (\d+)/(\d+)MB"),
    "swap_used_mb": re.compile(r"SWAP (\d+)/(\d+)MB"),
    "emc_pct": re.compile(r"EMC_FREQ (\d+)%@(\d+)"),
    # Some releases bracket the clock, some do not.
    "gpu_pct": re.compile(r"GR3D_FREQ (\d+)%@\[?(\d+)"),
    "tj_c": re.compile(r"tj@([\d.]+)C"),
    # tegrastats prints instantaneous/average. The average is cumulative over
    # the whole log, so averaging it across samples would double-average and
    # fold the idle brackets back in. Only the instantaneous value is used.
    "vdd_in_mw": re.compile(r"VDD_IN (\d+)mW/(\d+)mW"),
    "cpu": re.compile(r"CPU \[([^\]]+)\]"),
}
CORE = re.compile(r"(\d+)%@(\d+)")


def parse_line(line: str) -> Optional[Dict[str, float]]:
    gpu = PATTERNS["gpu_pct"].search(line)
    if not gpu:
        return None
    sample = {"gpu_pct": float(gpu.group(1)), "gpu_mhz": float(gpu.group(2))}

    emc = PATTERNS["emc_pct"].search(line)
    if emc:
        sample["emc_pct"] = float(emc.group(1))
        sample["emc_mhz"] = float(emc.group(2))
    for key, field in (("ram_used_mb", "ram_used_mb"), ("swap_used_mb", "swap_used_mb")):
        match = PATTERNS[key].search(line)
        if match:
            sample[field] = float(match.group(1))
    tj = PATTERNS["tj_c"].search(line)
    if tj:
        sample["tj_c"] = float(tj.group(1))
    vdd = PATTERNS["vdd_in_mw"].search(line)
    if vdd:
        sample["vdd_in_w"] = float(vdd.group(1)) / 1000.0
    cpu = PATTERNS["cpu"].search(line)
    if cpu:
        loads = [float(pct) for pct, _ in CORE.findall(cpu.group(1))]
        if loads:
            sample["cpu_busiest_pct"] = max(loads)
            sample["cpu_total_pct"] = sum(loads)
    return sample


def busy_runs(
    samples: List[Dict[str, float]], threshold: float
) -> List[List[Dict[str, float]]]:
    """Contiguous stretches above the busy threshold, in order."""
    runs: List[List[Dict[str, float]]] = []
    current: List[Dict[str, float]] = []
    for sample in samples:
        if sample["gpu_pct"] > threshold:
            current.append(sample)
        elif current:
            runs.append(current)
            current = []
    if current:
        runs.append(current)
    return runs


def trim_edges(
    runs: List[List[Dict[str, float]]], edge: int
) -> Dict[str, object]:
    """Drop `edge` samples from each end of each run.

    A run too short to survive trimming is dropped whole: it is all edge, and
    a one-second blip above the threshold is not a measurement of anything.
    """
    kept: List[Dict[str, float]] = []
    dropped_runs = 0
    for run in runs:
        if len(run) > 2 * edge:
            kept.extend(run[edge : len(run) - edge])
        else:
            dropped_runs += 1
    return {"samples": kept, "dropped_short_runs": dropped_runs}


# A clock this close to the ceiling is the sampling interval, not the governor.
_AT_CEILING = 0.98


def clock_verdict(gpu_mhz: Dict[str, float]) -> str:
    ceiling = gpu_mhz["max"]
    low = gpu_mhz["min"]
    share = low / ceiling if ceiling else 0.0
    n = gpu_mhz["n"]
    if low == ceiling:
        return (
            f"GPU clock pinned at {ceiling:.0f} MHz for all {n} samples.\n"
            "No sag, so this run was neither thermally nor power throttled."
        )
    if share >= _AT_CEILING:
        return (
            f"GPU clock held the ceiling: {low:.0f} - {ceiling:.0f} MHz over {n} "
            f"samples, the low being {share * 100:.1f}% of the high.\n"
            "A spread this small is tegrastats averaging over its interval, not\n"
            "the governor stepping down, so this run was not throttled."
        )
    return (
        f"GPU clock sagged: {low:.0f} - {ceiling:.0f} MHz over {n} samples, the low\n"
        f"being {share * 100:.1f}% of the high. That is below the power mode's\n"
        "ceiling for long enough to matter. Check tj and VDD_IN against the mode's\n"
        "budget before reading anything else in this table."
    )


def stats(samples: List[Dict[str, float]], field: str) -> Optional[Dict[str, float]]:
    values = [s[field] for s in samples if field in s]
    if not values:
        return None
    out = {
        "n": len(values),
        "min": min(values),
        "p50": percentile(values, 50),
        "p90": percentile(values, 90),
        "max": max(values),
    }
    return out


# (field, label, unit, decimals). Power and temperature carry a decimal
# because 16 W and 16.9 W are different answers about a 15W power mode.
FIELDS = [
    ("gpu_pct", "GPU utilisation", "%", 0),
    ("gpu_mhz", "GPU clock", "MHz", 0),
    ("emc_pct", "EMC utilisation", "%", 0),
    ("emc_mhz", "EMC clock", "MHz", 0),
    ("cpu_busiest_pct", "CPU, busiest core", "%", 0),
    ("cpu_total_pct", "CPU, summed over cores", "%", 0),
    ("ram_used_mb", "system RAM used", "MB", 0),
    ("swap_used_mb", "swap used", "MB", 0),
    ("tj_c", "tj", "C", 1),
    ("vdd_in_w", "VDD_IN", "W", 1),
]


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("logfile")
    p.add_argument(
        "--busy-above",
        type=float,
        default=50.0,
        help="GPU utilisation %% above which a sample counts as busy (default 50)",
    )
    p.add_argument(
        "--trim-edges",
        type=int,
        default=1,
        help="samples to drop from each end of each busy stretch (default 1); "
        "0 keeps them, which puts interval-averaged values in the minimum column",
    )
    p.add_argument("--out", help="write the summary as JSON")
    args = p.parse_args()

    with open(args.logfile) as fh:
        samples = [s for s in (parse_line(line) for line in fh) if s]
    if not samples:
        raise SystemExit(f"no tegrastats samples parsed from {args.logfile}")

    runs = busy_runs(samples, args.busy_above)
    trimmed = trim_edges(runs, args.trim_edges)
    busy = trimmed["samples"]
    idle = [s for s in samples if s["gpu_pct"] <= args.busy_above]
    untrimmed = sum(len(run) for run in runs)
    if not busy:
        raise SystemExit(
            f"no busy window survived trimming: {untrimmed} of {len(samples)} "
            f"samples were above {args.busy_above}% GPU, in {len(runs)} stretch(es). "
            "Either the run was not logged or --busy-above is wrong."
        )

    summary = {
        "logfile": os.path.basename(args.logfile),
        "samples": len(samples),
        "busy_above_gpu_pct": args.busy_above,
        "busy_stretches": len(runs),
        "trim_edges": args.trim_edges,
        "busy_samples": len(busy),
        "busy_samples_before_trim": untrimmed,
        "dropped_short_runs": trimmed["dropped_short_runs"],
        "idle_samples": len(idle),
        "busy": {field: stats(busy, field) for field, _, _, _ in FIELDS},
        "idle": {field: stats(idle, field) for field, _, _, _ in FIELDS},
    }

    print(f"{len(samples)} samples at 1 Hz: {untrimmed} busy, {len(idle)} idle")
    print(f"(busy means GPU utilisation above {args.busy_above:.0f}%)")
    print(
        f"{len(runs)} busy stretch(es), {args.trim_edges} sample(s) trimmed from each "
        f"end: {len(busy)} remain"
    )
    if trimmed["dropped_short_runs"]:
        print(
            f"{trimmed['dropped_short_runs']} stretch(es) too short to trim were "
            "dropped whole"
        )
    print()
    print(f"{'quantity':<26}{'busy p50':>12}{'busy min':>12}{'busy max':>12}{'idle p50':>12}")
    for field, label, unit, digits in FIELDS:
        b, i = summary["busy"].get(field), summary["idle"].get(field)
        if not b:
            continue
        cells = [f"{b[k]:.{digits}f}" for k in ("p50", "min", "max")]
        cells.append(f"{i['p50']:.{digits}f}" if i else "-")
        print(f"{label + ' (' + unit + ')':<26}" + "".join(f"{c:>12}" for c in cells))

    print()
    print(clock_verdict(summary["busy"]["gpu_mhz"]))

    if args.out:
        os.makedirs(os.path.dirname(os.path.abspath(args.out)), exist_ok=True)
        with open(args.out, "w") as fh:
            json.dump(summary, fh, indent=2, sort_keys=True)
            fh.write("\n")
        print(f"\nwrote {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
