#!/usr/bin/env python3
"""Summarise a tegrastats log over the window where the GPU was working.

The Gate 3 evidence table started life as three jtop screenshots, read off at
three arbitrary moments. Screenshots cannot answer the question the table is
there to answer -- did the GPU clock *hold* at the power mode's ceiling, or
sag partway through -- and they cannot be regenerated by anyone else. A 1 Hz
tegrastats log can, so this parses one.

    sudo tegrastats --interval 1000 --logfile run.log   # in one shell
    ...                                                 # the run, in another
    sudo tegrastats --stop
    python3 tools/summarize_tegrastats.py run.log

Samples are split into busy and idle by GPU utilisation, because a log always
brackets the run with idle time and mixing the two produces an average that
describes neither. The split is reported so the choice is visible.

One sample at each edge of each busy stretch is then dropped. tegrastats
reports the *mean* over its interval, so a sample straddling the start or end
of the run averages a working GPU with an idle one. Left in, those samples
put impossible values in the minimum column -- 0% CPU and 11.5 W during an
inference -- and make the clock look like it sagged when it did not.
"""

from __future__ import annotations

import argparse
import json
import os
import re
import sys
from datetime import datetime
from typing import Dict, List, Optional, Tuple

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from telemetry.metrics import percentile

# Fields vary between L4T releases, so each is matched independently and a
# missing one is skipped rather than failing the parse.
PATTERNS = {
    "ram_used_mb": re.compile(r"RAM (\d+)/(\d+)MB"),
    "swap_used_mb": re.compile(r"SWAP (\d+)/(\d+)MB"),
    "emc_pct": re.compile(r"EMC_FREQ (\d+)%@(\d+)"),
    # Some releases bracket the clock, some do not.
    "gpu_pct": re.compile(r"GR3D_FREQ (\d+)%@\[?(\d+)"),
    "tj_c": re.compile(r"tj@([\d.]+)C"),
    # tegrastats prints instantaneous/average. The average is cumulative over
    # the whole log, so averaging it across samples would double-average and
    # fold the idle brackets back in. Only the instantaneous value is used.
    "vdd_in_mw": re.compile(r"VDD_IN (\d+)mW/(\d+)mW"),
    "cpu": re.compile(r"CPU \[([^\]]+)\]"),
}
CORE = re.compile(r"(\d+)%@(\d+)")


STAMP = re.compile(r"^(\d\d-\d\d-\d{4} \d\d:\d\d:\d\d)")


def parse_line(line: str) -> Optional[Dict[str, float]]:
    gpu = PATTERNS["gpu_pct"].search(line)
    if not gpu:
        return None
    sample = {"gpu_pct": float(gpu.group(1)), "gpu_mhz": float(gpu.group(2))}
    stamp = STAMP.match(line)
    if stamp:
        sample["ts"] = datetime.strptime(
            stamp.group(1), "%m-%d-%Y %H:%M:%S"
        ).timestamp()

    emc = PATTERNS["emc_pct"].search(line)
    if emc:
        sample["emc_pct"] = float(emc.group(1))
        sample["emc_mhz"] = float(emc.group(2))
    for key, field in (("ram_used_mb", "ram_used_mb"), ("swap_used_mb", "swap_used_mb")):
        match = PATTERNS[key].search(line)
        if match:
            sample[field] = float(match.group(1))
    tj = PATTERNS["tj_c"].search(line)
    if tj:
        sample["tj_c"] = float(tj.group(1))
    vdd = PATTERNS["vdd_in_mw"].search(line)
    if vdd:
        sample["vdd_in_w"] = float(vdd.group(1)) / 1000.0
    cpu = PATTERNS["cpu"].search(line)
    if cpu:
        loads = [float(pct) for pct, _ in CORE.findall(cpu.group(1))]
        if loads:
            sample["cpu_busiest_pct"] = max(loads)
            sample["cpu_total_pct"] = sum(loads)
    return sample


def segments(
    samples: List[Dict[str, float]], max_gap_s: float
) -> List[Tuple[int, int]]:
    """Split on time discontinuities. `[(start, stop), ...]`, stop exclusive.

    `tegrastats --logfile` appends, so reusing a filename across runs leaves
    one file holding several. Averaging across the join produced a log of
    1576 samples spanning 2194 seconds, 65 busy stretches instead of 33, and
    an "idle" CPU figure higher than the busy one -- because the idle samples
    were two runs' weight-loading phases, which are CPU-bound with the GPU
    parked.
    """
    if not samples or "ts" not in samples[0]:
        return [(0, len(samples))]
    bounds = [0]
    for i in range(1, len(samples)):
        if samples[i]["ts"] - samples[i - 1]["ts"] > max_gap_s:
            bounds.append(i)
    bounds.append(len(samples))
    return list(zip(bounds, bounds[1:]))


def busy_runs(
    samples: List[Dict[str, float]], threshold: float
) -> List[List[Dict[str, float]]]:
    """Contiguous stretches above the busy threshold, in order."""
    runs: List[List[Dict[str, float]]] = []
    current: List[Dict[str, float]] = []
    for sample in samples:
        if sample["gpu_pct"] > threshold:
            current.append(sample)
        elif current:
            runs.append(current)
            current = []
    if current:
        runs.append(current)
    return runs


def trim_edges(
    runs: List[List[Dict[str, float]]], edge: int
) -> Dict[str, object]:
    """Drop `edge` samples from each end of each run.

    A run too short to survive trimming is dropped whole: it is all edge, and
    a one-second blip above the threshold is not a measurement of anything.
    """
    kept: List[Dict[str, float]] = []
    dropped_runs = 0
    for run in runs:
        if len(run) > 2 * edge:
            kept.extend(run[edge : len(run) - edge])
        else:
            dropped_runs += 1
    return {"samples": kept, "dropped_short_runs": dropped_runs}


def drift(
    run: List[Dict[str, float]], window: int
) -> Optional[Dict[str, Dict[str, float]]]:
    """Mean of the first `window` samples against the last, within one stretch.

    A distribution says what a run cost; it cannot say whether the run had
    settled. The same 142 samples that show no clock sag also show tj climbing
    6.6 C from the first ten seconds to the last, still rising at the end --
    which scopes "not thermally limited" to a run of this length rather than
    to the board.

    Compared within a single stretch, never across the whole busy set: the
    stretches are different activities (weight loading, warmup, the measured
    runs) and a first-to-last across all of them would compare loading with
    inference and call the difference drift.
    """
    # Two windows that overlap would share samples, double-counting them and
    # understating the movement. Disjoint is the only requirement.
    if len(run) < 2 * window:
        return None
    out = {}
    for field, _, _, _ in FIELDS:
        head = [s[field] for s in run[:window] if field in s]
        tail = [s[field] for s in run[-window:] if field in s]
        if not head or not tail:
            continue
        first, last = sum(head) / len(head), sum(tail) / len(tail)
        out[field] = {"first": first, "last": last, "delta": last - first}
    return out


# A clock this close to the ceiling is the sampling interval, not the governor.
_AT_CEILING = 0.98
# The floor is read at this percentile rather than at the minimum. One sample
# in 534 sat at 509 MHz while the other 533 held 611, and a min-versus-max
# verdict called that throttling. Throttling is a sustained condition, so the
# estimator has to be one too.
_FLOOR_PERCENTILE = 10


def clock_verdict(values: List[float]) -> str:
    ceiling = max(values)
    floor = percentile(values, _FLOOR_PERCENTILE)
    low = min(values)
    below = sum(1 for v in values if v < _AT_CEILING * ceiling)
    n = len(values)
    share = floor / ceiling if ceiling else 0.0
    dips = (
        f"{below} of {n} samples dipped below {_AT_CEILING * ceiling:.0f} MHz,\n"
        f"the lowest {low:.0f}."
    )
    if below == 0:
        return (
            f"GPU clock held {ceiling:.0f} MHz across all {n} busy samples.\n"
            "No sag, so this run was neither thermally nor power throttled."
        )
    if share >= _AT_CEILING:
        return (
            f"GPU clock held the ceiling: p{_FLOOR_PERCENTILE} is {floor:.0f} MHz "
            f"against a {ceiling:.0f} MHz high, {share * 100:.1f}% of it.\n"
            f"{dips} Isolated dips are not throttling, which is a\n"
            "sustained condition; a run at the ceiling for 90% of its samples\n"
            "was not clock-limited below its power mode."
        )
    return (
        f"GPU clock sagged: p{_FLOOR_PERCENTILE} is {floor:.0f} MHz against a "
        f"{ceiling:.0f} MHz high, {share * 100:.1f}% of it.\n"
        f"{dips} That is below the power mode's ceiling often enough\n"
        "to matter. Check tj and VDD_IN against the mode's budget before\n"
        "reading anything else in this table."
    )


def stats(samples: List[Dict[str, float]], field: str) -> Optional[Dict[str, float]]:
    values = [s[field] for s in samples if field in s]
    if not values:
        return None
    out = {
        "n": len(values),
        "min": min(values),
        "p50": percentile(values, 50),
        "p90": percentile(values, 90),
        "max": max(values),
    }
    return out


# (field, label, unit, decimals). Power and temperature carry a decimal
# because 16 W and 16.9 W are different answers about a 15W power mode.
FIELDS = [
    ("gpu_pct", "GPU utilisation", "%", 0),
    ("gpu_mhz", "GPU clock", "MHz", 0),
    ("emc_pct", "EMC utilisation", "%", 0),
    ("emc_mhz", "EMC clock", "MHz", 0),
    ("cpu_busiest_pct", "CPU, busiest core", "%", 0),
    ("cpu_total_pct", "CPU, summed over cores", "%", 0),
    ("ram_used_mb", "system RAM used", "MB", 0),
    ("swap_used_mb", "swap used", "MB", 0),
    ("tj_c", "tj", "C", 1),
    ("vdd_in_w", "VDD_IN", "W", 1),
]


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("logfile")
    p.add_argument(
        "--busy-above",
        type=float,
        default=50.0,
        help="GPU utilisation %% above which a sample counts as busy (default 50)",
    )
    p.add_argument(
        "--trim-edges",
        type=int,
        default=1,
        help="samples to drop from each end of each busy stretch (default 1); "
        "0 keeps them, which puts interval-averaged values in the minimum column",
    )
    p.add_argument(
        "--max-gap-s",
        type=float,
        default=5.0,
        help="a time step larger than this starts a new run (default 5)",
    )
    p.add_argument(
        "--segment",
        type=int,
        help="which run to summarise when the log holds several, 1-based; "
        "the last one by default, since that is usually the one just finished",
    )
    p.add_argument(
        "--drift-window",
        type=int,
        default=10,
        help="samples at each end of the longest busy stretch to compare, for "
        "whether the run had settled (default 10)",
    )
    p.add_argument("--out", help="write the summary as JSON")
    args = p.parse_args()

    with open(args.logfile) as fh:
        everything = [s for s in (parse_line(line) for line in fh) if s]
    if not everything:
        raise SystemExit(f"no tegrastats samples parsed from {args.logfile}")

    found = segments(everything, args.max_gap_s)
    if len(found) > 1:
        print(
            f"{args.logfile} holds {len(found)} runs "
            f"(gaps over {args.max_gap_s:.0f} s). tegrastats --logfile appends, "
            "so a reused filename accumulates them:"
        )
        for n, (start, stop) in enumerate(found, 1):
            first = datetime.fromtimestamp(everything[start]["ts"]).strftime("%H:%M:%S")
            last = datetime.fromtimestamp(everything[stop - 1]["ts"]).strftime("%H:%M:%S")
            print(f"  [{n}] {stop - start:5d} samples  {first} - {last}")
        print()
    chosen = (args.segment or len(found)) - 1
    if not 0 <= chosen < len(found):
        raise SystemExit(f"--segment must be 1..{len(found)}")
    start, stop = found[chosen]
    samples = everything[start:stop]
    if len(found) > 1:
        print(f"summarising run [{chosen + 1}] of {len(found)}; --segment picks another\n")

    runs = busy_runs(samples, args.busy_above)
    trimmed = trim_edges(runs, args.trim_edges)
    busy = trimmed["samples"]
    idle = [s for s in samples if s["gpu_pct"] <= args.busy_above]
    untrimmed = sum(len(run) for run in runs)
    if not busy:
        raise SystemExit(
            f"no busy window survived trimming: {untrimmed} of {len(samples)} "
            f"samples were above {args.busy_above}% GPU, in {len(runs)} stretch(es). "
            "Either the run was not logged or --busy-above is wrong."
        )

    summary = {
        "logfile": os.path.basename(args.logfile),
        "runs_in_logfile": len(found),
        "run_summarised": chosen + 1,
        "samples": len(samples),
        "busy_above_gpu_pct": args.busy_above,
        "busy_stretches": len(runs),
        "trim_edges": args.trim_edges,
        "busy_samples": len(busy),
        "busy_samples_before_trim": untrimmed,
        "dropped_short_runs": trimmed["dropped_short_runs"],
        "idle_samples": len(idle),
        "busy": {field: stats(busy, field) for field, _, _, _ in FIELDS},
        "idle": {field: stats(idle, field) for field, _, _, _ in FIELDS},
    }

    # The longest stretch is the measured work: warmup and weight loading are
    # their own, shorter stretches.
    longest = max(runs, key=len)
    longest_trimmed = longest[args.trim_edges : len(longest) - args.trim_edges]
    moved = drift(longest_trimmed, args.drift_window)
    summary["drift"] = {
        "stretch_samples": len(longest_trimmed),
        "window": args.drift_window,
        "fields": moved,
    }

    print(f"{len(samples)} samples at 1 Hz: {untrimmed} busy, {len(idle)} idle")
    print(f"(busy means GPU utilisation above {args.busy_above:.0f}%)")
    print(
        f"{len(runs)} busy stretch(es), {args.trim_edges} sample(s) trimmed from each "
        f"end: {len(busy)} remain"
    )
    if trimmed["dropped_short_runs"]:
        print(
            f"{trimmed['dropped_short_runs']} stretch(es) too short to trim were "
            "dropped whole"
        )
    print()
    print(f"{'quantity':<26}{'busy p50':>12}{'busy min':>12}{'busy max':>12}{'idle p50':>12}")
    for field, label, unit, digits in FIELDS:
        b, i = summary["busy"].get(field), summary["idle"].get(field)
        if not b:
            continue
        cells = [f"{b[k]:.{digits}f}" for k in ("p50", "min", "max")]
        cells.append(f"{i['p50']:.{digits}f}" if i else "-")
        print(f"{label + ' (' + unit + ')':<26}" + "".join(f"{c:>12}" for c in cells))

    if moved:
        print(
            f"\ndrift within the longest stretch ({len(longest_trimmed)} samples), "
            f"first {args.drift_window} against last {args.drift_window}:\n"
        )
        print(f"{'quantity':<26}{'first':>12}{'last':>12}{'delta':>12}")
        for field, label, unit, digits in FIELDS:
            d = moved.get(field)
            if not d:
                continue
            print(
                f"{label + ' (' + unit + ')':<26}"
                f"{d['first']:>12.{digits}f}{d['last']:>12.{digits}f}"
                f"{d['delta']:>+12.{digits}f}"
            )
        print("\nA quantity still moving at the end had not settled in this run.")
    else:
        print(
            f"\nlongest stretch is {len(longest_trimmed)} samples, too short for a "
            f"first-{args.drift_window} against last-{args.drift_window} comparison"
        )

    print()
    print(clock_verdict([s["gpu_mhz"] for s in busy]))

    if args.out:
        os.makedirs(os.path.dirname(os.path.abspath(args.out)), exist_ok=True)
        with open(args.out, "w") as fh:
            json.dump(summary, fh, indent=2, sort_keys=True)
            fh.write("\n")
        print(f"\nwrote {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
