#!/usr/bin/env python3
"""Summarise a tegrastats log over the window where the GPU was working.

The Gate 3 evidence table started life as three jtop screenshots, read off at
three arbitrary moments. Screenshots cannot answer the question the table is
there to answer -- did the GPU clock *hold* at the power mode's ceiling, or
sag partway through -- and they cannot be regenerated by anyone else. A 1 Hz
tegrastats log can, so this parses one.

    sudo tegrastats --interval 1000 --logfile run.log   # in one shell
    ...                                                 # the run, in another
    sudo tegrastats --stop
    python3 tools/summarize_tegrastats.py run.log

Samples are split into busy and idle by GPU utilisation, because a log always
brackets the run with idle time and mixing the two produces an average that
describes neither. The split is reported so the choice is visible.
"""

from __future__ import annotations

import argparse
import json
import os
import re
import sys
from typing import Dict, List, Optional

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from telemetry.metrics import percentile

# Fields vary between L4T releases, so each is matched independently and a
# missing one is skipped rather than failing the parse.
PATTERNS = {
    "ram_used_mb": re.compile(r"RAM (\d+)/(\d+)MB"),
    "swap_used_mb": re.compile(r"SWAP (\d+)/(\d+)MB"),
    "emc_pct": re.compile(r"EMC_FREQ (\d+)%@(\d+)"),
    # Some releases bracket the clock, some do not.
    "gpu_pct": re.compile(r"GR3D_FREQ (\d+)%@\[?(\d+)"),
    "tj_c": re.compile(r"tj@([\d.]+)C"),
    # tegrastats prints instantaneous/average. The average is cumulative over
    # the whole log, so averaging it across samples would double-average and
    # fold the idle brackets back in. Only the instantaneous value is used.
    "vdd_in_mw": re.compile(r"VDD_IN (\d+)mW/(\d+)mW"),
    "cpu": re.compile(r"CPU \[([^\]]+)\]"),
}
CORE = re.compile(r"(\d+)%@(\d+)")


def parse_line(line: str) -> Optional[Dict[str, float]]:
    gpu = PATTERNS["gpu_pct"].search(line)
    if not gpu:
        return None
    sample = {"gpu_pct": float(gpu.group(1)), "gpu_mhz": float(gpu.group(2))}

    emc = PATTERNS["emc_pct"].search(line)
    if emc:
        sample["emc_pct"] = float(emc.group(1))
        sample["emc_mhz"] = float(emc.group(2))
    for key, field in (("ram_used_mb", "ram_used_mb"), ("swap_used_mb", "swap_used_mb")):
        match = PATTERNS[key].search(line)
        if match:
            sample[field] = float(match.group(1))
    tj = PATTERNS["tj_c"].search(line)
    if tj:
        sample["tj_c"] = float(tj.group(1))
    vdd = PATTERNS["vdd_in_mw"].search(line)
    if vdd:
        sample["vdd_in_w"] = float(vdd.group(1)) / 1000.0
    cpu = PATTERNS["cpu"].search(line)
    if cpu:
        loads = [float(pct) for pct, _ in CORE.findall(cpu.group(1))]
        if loads:
            sample["cpu_busiest_pct"] = max(loads)
            sample["cpu_total_pct"] = sum(loads)
    return sample


def stats(samples: List[Dict[str, float]], field: str) -> Optional[Dict[str, float]]:
    values = [s[field] for s in samples if field in s]
    if not values:
        return None
    out = {
        "n": len(values),
        "min": min(values),
        "p50": percentile(values, 50),
        "p90": percentile(values, 90),
        "max": max(values),
    }
    return out


# (field, label, unit, decimals). Power and temperature carry a decimal
# because 16 W and 16.9 W are different answers about a 15W power mode.
FIELDS = [
    ("gpu_pct", "GPU utilisation", "%", 0),
    ("gpu_mhz", "GPU clock", "MHz", 0),
    ("emc_pct", "EMC utilisation", "%", 0),
    ("emc_mhz", "EMC clock", "MHz", 0),
    ("cpu_busiest_pct", "CPU, busiest core", "%", 0),
    ("cpu_total_pct", "CPU, summed over cores", "%", 0),
    ("ram_used_mb", "system RAM used", "MB", 0),
    ("swap_used_mb", "swap used", "MB", 0),
    ("tj_c", "tj", "C", 1),
    ("vdd_in_w", "VDD_IN", "W", 1),
]


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("logfile")
    p.add_argument(
        "--busy-above",
        type=float,
        default=50.0,
        help="GPU utilisation %% above which a sample counts as busy (default 50)",
    )
    p.add_argument("--out", help="write the summary as JSON")
    args = p.parse_args()

    with open(args.logfile) as fh:
        samples = [s for s in (parse_line(line) for line in fh) if s]
    if not samples:
        raise SystemExit(f"no tegrastats samples parsed from {args.logfile}")

    busy = [s for s in samples if s["gpu_pct"] > args.busy_above]
    idle = [s for s in samples if s["gpu_pct"] <= args.busy_above]
    if not busy:
        raise SystemExit(
            f"no sample above {args.busy_above}% GPU: either the run was not "
            f"logged or the threshold is wrong"
        )

    summary = {
        "logfile": os.path.basename(args.logfile),
        "samples": len(samples),
        "busy_above_gpu_pct": args.busy_above,
        "busy_samples": len(busy),
        "idle_samples": len(idle),
        "busy": {field: stats(busy, field) for field, _, _, _ in FIELDS},
        "idle": {field: stats(idle, field) for field, _, _, _ in FIELDS},
    }

    print(f"{len(samples)} samples at 1 Hz: {len(busy)} busy, {len(idle)} idle")
    print(f"(busy means GPU utilisation above {args.busy_above:.0f}%)\n")
    print(f"{'quantity':<26}{'busy p50':>12}{'busy min':>12}{'busy max':>12}{'idle p50':>12}")
    for field, label, unit, digits in FIELDS:
        b, i = summary["busy"].get(field), summary["idle"].get(field)
        if not b:
            continue
        cells = [f"{b[k]:.{digits}f}" for k in ("p50", "min", "max")]
        cells.append(f"{i['p50']:.{digits}f}" if i else "-")
        print(f"{label + ' (' + unit + ')':<26}" + "".join(f"{c:>12}" for c in cells))

    gpu = summary["busy"]["gpu_mhz"]
    if gpu["min"] == gpu["max"]:
        print(f"\nGPU clock pinned at {gpu['max']:.0f} MHz for all {gpu['n']} busy samples.")
        print("No clock sag, so this run was not thermally or power throttled.")
    else:
        print(f"\nGPU clock varied: {gpu['min']:.0f} - {gpu['max']:.0f} MHz over {gpu['n']} samples.")
        print("A clock below the power mode's ceiling means throttling. Check tj and VDD_IN.")

    if args.out:
        os.makedirs(os.path.dirname(os.path.abspath(args.out)), exist_ok=True)
        with open(args.out, "w") as fh:
            json.dump(summary, fh, indent=2, sort_keys=True)
            fh.write("\n")
        print(f"\nwrote {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
